lib/dogma/rules/windows_line_endings.ex
test/dogma/rules/windows_line_endings_test.exs

Add rule for windows line endings

---

lib/dogma/rules/function_name.ex
lib/dogma/rules/sets/all.ex
test/dogma/rules/function_name_test.exs

Add rule for function names in snake_case

---

lib/dogma/rules/function_arity.ex
lib/dogma/rules/sets/all.ex
test/dogma/rules/function_arity_test.exs

Add rule for function arity

---

lib/dogma/rules.ex

As discussed in commit 8f6eee3

Remove default prefix from configured ruleset.

---

lib/dogma/rules/module_doc.ex
test/dogma/rules/module_doc_test.exs

https://github.com/lpil/dogma/issues/92

Add module name to ModuleDoc rule errors

---

docs/rules.md
lib/dogma/rule_set/all.ex
lib/dogma/rules/literal_in_condition.ex
lib/dogma/rules/literal_in_interpolation.ex
lib/dogma/util/ast_node.ex
test/dogma/documentation/rules_list_test.exs
test/dogma/rules/literal_in_interpolation_test.exs
test/dogma/util/ast_node_test.exs

Hopefully this is what you're looking for in https://github.com/lpil/dogma/issues/46 . Let me know if there are any test case you'd like me to add or changes you'd like made!

Add literal in interpolation rule

---

docs/rules.md
lib/dogma/rules/variable_name.ex
test/dogma/rules/variable_name_test.exs

https://github.com/lpil/dogma/issues/89

Destructured assignment variable names

---

README.md
docs/formatters.md
lib/dogma/documentation/formatters_list.ex
lib/dogma/formatter.ex
lib/dogma/formatter/flycheck.ex
lib/dogma/formatter/simple.ex
lib/mix/tasks/dogma.ex
scripts/generate_documentation.exs
test/dogma/documentation/formatters_list_test.exs
test/dogma/formatter_test.exs

Documentation Generator for Formatters

---

docs/rules.md
lib/dogma/rule_set/all.ex
lib/dogma/rules/final_condition.ex
test/dogma/rules/final_condition_test.exs
test/dogma/util/cyclomatic_complexity_test.exs

From the community style guide.

New Rule: Always use `true` as the final condition of a `cond` statement

---

docs/formatters.md
lib/dogma/formatter.ex
lib/dogma/formatter/json.ex
mix.exs
test/dogma/formatter/json_test.exs

Add JSON formatter

---

lib/dogma/util/ast_node.ex

This cleans up some code to adhere to the style guide we are sometimes
referring to.
So this is just housekeeping.

Clean up code in Dogma.Util.ASTNode

---

lib/dogma/documentation/formatters_list.ex
lib/dogma/rule/function_name.ex
lib/dogma/rule/module_attribute_name.ex
lib/dogma/rule/module_name.ex
lib/dogma/rule/variable_name.ex
lib/dogma/util/name.ex
test/dogma/rule/variable_name_test.exs

So probably_snake_case? becomes snake_case? and so on ...
Discussed here: https://github.com/lpil/dogma/issues/117

Replace probably_* functions with decisivei ones

---

lib/dogma/rule/bare_pipe_chain_start.ex
test/dogma/rule/bare_pipe_chain_start_test.exs

Fixes #120 (also adds a test to ensure it stays fixed ^_^)

Fix BarePipeChainStart for ranges

---

.travis.yml
lib/dogma/rule/exception_name.ex
lib/dogma/rule/final_condition.ex
lib/dogma/rule/function_arity.ex
lib/dogma/rule/hard_tabs.ex
lib/dogma/rule/line_length.ex
lib/dogma/rule/literal_in_condition.ex
lib/dogma/rule/literal_in_interpolation.ex
lib/dogma/rule/module_attribute_name.ex
lib/dogma/rule/module_name.ex
lib/dogma/rule/negated_if_unless.ex
lib/dogma/rule/predicate_name.ex
lib/dogma/rule/quotes_in_string.ex
lib/dogma/rule/semicolon.ex
lib/dogma/rule/trailing_blank_lines.ex
lib/dogma/rule/trailing_whitespace.ex
lib/dogma/rule/unless_else.ex
lib/dogma/rule/windows_line_endings.ex
lib/dogma/script.ex
test/dogma/rule/hard_tabs_test.exs
test/dogma/script_test.exs

This PR ensures compatibility for 1.0.x and 1.1.x - that's basically it. :wink:

Support for Elixir 1.1.x

---

lib/dogma/rule/quotes_in_string.ex
test/dogma/rule/quotes_in_string_test.exs

Fix interpolation in strings

---

docs/configuration.md

Having this in the documentation would have saved me a lot of time and hair 😚

Update configuration.md show how to override rule

---

.gitignore
docs/rules.md
lib/dogma/rule/taken_name.ex
lib/dogma/rule_set/all.ex
test/dogma/rule/taken_name_test.exs

This PR adds TakenName rule described in #151 
Todos: 
--------

TakenName rule

---

README.md

Link updated to https://hexdocs.pm/dogma/api-reference.html

Developer docs link correction

---

lib/dogma/reporter/flycheck.ex
lib/dogma/script.ex
test/dogma/reporter/flycheck_test.exs
test/dogma/script_test.exs

Follow-up to #205, I used the opportunity to get my feet wet with ExUnit :)

Improve messages for syntax errors

---

lib/dogma/util/ast_node.ex
test/dogma/rule/literal_in_condition_test.exs
test/dogma/util/ast_node_test.exs

Fix LiteralInCondition for tuples with variables

---

lib/dogma/rule/function_parentheses.ex

I realized I could refactor my original code here by simplifying it into two functions that match when there is a rule being broken. I think this code is easier to understand.
Any feedback on how to format these functions with headers that exceed the 80 character line length limit? Let me know what you prefer.

Clean up FunctionParentheses rule

---

lib/dogma/rule/pipeline_start.ex
test/dogma/rule/pipeline_start_test.exs

Fixes https://github.com/lpil/dogma/issues/228

Add exception for ++ to PipelineStart

---

lib/dogma.ex

First, thanks for dogma. I use it a lot and has helped me to write better code in Elixir. Its just a spelling fix and little more addition of what dogma is in moduledoc

fix spelling and add little documentation for module

---

.gitignore

`test/dogma` was being hidden/ignored by my IDE setting.. thought would be more appropriate to do this.

only ignore dogma in root

---

lib/dogma/rule/pipeline_start.ex
test/dogma/rule/pipeline_start_test.exs

Ignore value placeholders
